"""
Parse CSV files generated by qualtrics and load into Student
and Club objects for matching
"""

from match import Student, Club
import pandas as pd

# Maps student question to club question
question_map = {
        'Q1' : 'Q2',
        'Q3' : 'Q17',
        'Q12' : 'Q6',
        'Q13': 'Q7',
        'Q4' : 'Q9',
        'Q5' : 'Q10',
        'Q6' : 'Q11',
        'Q7' : 'Q12',
        'Q8' : 'Q13',
        'Q9_1' : 'Q14_1',
        'Q9_2' : 'Q14_2',
        'Q9_3' : 'Q14_3',
        'Q9_4' : 'Q14_4',
        'Q16_1' : 'Q16_1',
        'Q16_2' : 'Q16_2',
        'Q16_3' : 'Q16_3',
        'Q16_4' : 'Q16_4',
        'Q16_5' : 'Q16_5'
        }

def get_questions():
    student_qs = list(question_map.keys())
    student_qs.remove('Q1')
    student_qs.remove('Q3')
    club_qs = [question_map[q] for q in student_qs]
    if len(student_qs) != len(club_qs):
        raise ValueError("Not all questions aligned!")
    qids = list(range(len(student_qs)))
    return student_qs, club_qs, qids


def load_students(fp, questions, qids):
    df = pd.read_csv(fp)
    students = []
    for index, row in df.iterrows():
        name = row['Q14']
        email = row['Q15']
        affinity = row['Q10'] != ""
        answers = row[questions].tolist()
        s = Student(name, email, affinity, qids, answers)
        students.append(s)
    return students

def load_clubs(fp, questions, qids):
    df = pd.read_csv(fp)
    clubs = []
    for index, row in df.iterrows():
        name = row['Q1']
        contact = row['Q20_1']
        email = row['Q20_2']
        answers = row[questions].tolist()
        c = Club(name, contact, email, qids, answers)
        clubs.append(c)
    return clubs

def main():
    clubs_fp = 'test-data/clubs.csv'
    student_qs, club_qs, qids = get_questions()
    clubs = load_clubs(clubs_fp, club_qs, qids)
    print([str(club) for club in clubs])

if __name__ == '__main__':
    main()
